application: sailing-project
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bower_components
  static_dir: bower_components

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /data
  static_dir: data

- url: /templates
  static_dir: templates

- url: .*
  script: map.application

- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin


libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest