application: sailing-project
version: 1
runtime: python27
api_version: 1
threadsafe: no



handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bower_components
  static_dir: bower_components

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /data
  static_dir: data

- url: /static
  static_dir: static

- url: /templates
  static_dir: templates


- url: /_ah/mail/.+
  script: handle_incoming_email.py
  login: admin


- url: /email
  script: emailsender.py
  login: admin

- url: .*
  script: main.app

inbound_services:
- mail


libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest